# Generated by Django 4.2.20 on 2025-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acid_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
