# Generated by Django 4.2.20 on 2025-04-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
